create or replace procedure ADM_ACM_LOGIN
( P_USU_SIST IN EMPLEADO.USU_SIST%TYPE,
  P_CLAVE  IN EMPLEADO.CLAVE%TYPE,
  P_cursor OUT NOCOPY SYS_REFCURSOR )
as 
  V_USU_SIST EMPLEADO.USU_SIST%TYPE;
  V_CLAVE  EMPLEADO.CLAVE%TYPE;
begin
  V_USU_SIST := UPPER(P_USU_SIST);
  V_CLAVE := UPPER(P_CLAVE);

  open p_cursor for 
    SELECT E.CO_EMPL, A.DESC_AREA, USU_SIST, C.DESC_CARGO ,
         E.EST_EMPL, E.APE_PAT, E.APE_MAT, E.NOMBRE ,P.DNI ,
         E.FEC_MOD
  FROM EMPLEADO E ,AREA A, CARGO C ,PERSONA P
  WHERE A.CO_AREA = E.CO_AREA 
  AND C.CO_CARGO = E.CO_CARGO
  AND E.CO_EMPL = P.CO_EMPL 
  AND  E.USU_SIST= V_USU_SIST AND E.CLAVE =V_CLAVE;
end;
/
