create or replace procedure ADM_EMPL_FINDBYID
( P_CO_EMPL IN EMPLEADO.CO_EMPL%TYPE,
  P_CO_AREA OUT EMPLEADO.CO_AREA%TYPE,
  P_USU_SIST OUT EMPLEADO.USU_SIST%TYPE,
  P_CO_CARGO OUT EMPLEADO.CO_CARGO%TYPE,
  P_EST_EMPL OUT EMPLEADO.EST_EMPL%TYPE,
  P_APE_PAT OUT EMPLEADO.APE_PAT%TYPE,
  P_APE_MAT OUT EMPLEADO.APE_MAT%TYPE,
  P_NOMBRE OUT EMPLEADO.NOMBRE%TYPE
  )
as 
  --V_CO_AREA  EMPLEADO.CO_AREA%TYPE;
  --V_USU_SIST  EMPLEADO.USU_SIST%TYPE;
  --V_CO_CARGO  EMPLEADO.CO_CARGO%TYPE;
  --V_EST_EMPL  EMPLEADO.EST_EMPL%TYPE;
  --V_APE_PAT  EMPLEADO.APE_PAT%TYPE;
  --V_APE_MAT  EMPLEADO.APE_MAT%TYPE;
  --V_NOMBRE  EMPLEADO.NOMBRE%TYPE;
begin
    SELECT 
    CO_AREA,
    USU_SIST,
    CO_CARGO,
    EST_EMPL,
    APE_PAT,
    APE_MAT,
    NOMBRE
    INTO P_CO_AREA, P_USU_SIST, P_CO_CARGO, P_EST_EMPL,
     P_APE_PAT , P_APE_MAT ,P_NOMBRE
     FROM EMPLEADO
     WHERE CO_EMPL= P_CO_EMPL;       
end;
/
