create or replace procedure ADM_EMPL_GETEMPLEADOS
( P_APE_PAT IN EMPLEADO.APE_PAT%TYPE,
  P_APE_MAT IN EMPLEADO.APE_MAT%TYPE,
  P_NOMBRE IN EMPLEADO.NOMBRE%TYPE,
 P_cursor OUT NOCOPY SYS_REFCURSOR )
as 
  V_APE_PAT EMPLEADO.APE_PAT%TYPE;
  V_APE_MAT EMPLEADO.APE_MAT%TYPE;
  V_NOMBRE EMPLEADO.NOMBRE%TYPE;
begin
  V_APE_PAT := UPPER(P_APE_PAT) || '%';
  V_APE_MAT := UPPER(P_APE_MAT) || '%';
  V_NOMBRE :=  UPPER(P_NOMBRE) || '%';

  open P_cursor for 
    SELECT E.CO_EMPL, E.APE_PAT, E.APE_MAT, E.NOMBRE, E.EST_EMPL , USU_SIST, 
       C.DESC_CARGO ,
        --P.DNI ,
        E.FEC_MOD
    FROM EMPLEADO E ,AREA A, CARGO C --,PERSONA P
    WHERE A.CO_AREA = E.CO_AREA 
    AND C.CO_CARGO = E.CO_CARGO
    --AND E.CO_EMPL = P.CO_EMPL 
    AND E.APE_PAT LIKE V_APE_PAT
    AND E.APE_MAT LIKE V_APE_MAT
    AND E.NOMBRE LIKE V_NOMBRE;
end;
/
