--1 LOGIN
SELECT E.CO_EMPL, A.DESC_AREA, USU_SIST, C.DESC_CARGO ,
         E.EST_EMPL, E.APE_PAT, E.APE_MAT, E.NOMBRE ,P.DNI ,
          E.FEC_MOD
  FROM EMPLEADO E ,AREA A, CARGO C ,PERSONA P
  WHERE A.CO_AREA = E.CO_AREA 
  AND C.CO_CARGO = E.CO_CARGO
  AND E.CO_EMPL = P.CO_EMPL 
  AND  E.USU_SIST='BNIEVA' AND E.CLAVE ='BNIEVA'
  
--2 LISTA DE USUARIOS 
SELECT E.CO_EMPL, E.APE_PAT, E.APE_MAT, E.NOMBRE, E.EST_EMPL , E.USU_SIST, 
       C.DESC_CARGO , P.DNI ,E.FEC_MOD
  FROM EMPLEADO E ,AREA A, CARGO C ,PERSONA P
  WHERE A.CO_AREA = E.CO_AREA 
  AND C.CO_CARGO = E.CO_CARGO
  AND E.CO_EMPL = P.CO_EMPL 
  --AND  E.USU_SIST='BNIEVA' AND E.CLAVE ='BNIEVA'
  
--3 EDITAR USUARIO
UPDATE EMPLEADO
SET CO_AREA ='03' ,-- CO_CARGO='04'
FEC_MOD = SYSDATE
WHERE CO_EMPL='000001'







