/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.pp03app.view;

import java.awt.Font;
import javax.swing.JOptionPane;
import pe.egcc.pp03app.dto.PP03Dto;
import pe.egcc.pp03app.service.PP03Service;

/**
 *
 * @author Andy3
 */
public class PP03View extends javax.swing.JFrame {

    /**
     * Creates new form PP03View
     */
    public PP03View() {
        int LETTER_SIZE = 15;
        String ARIAL = "Arial";
        initComponents();
        this.setTitle("PP03App");
        lblPrecioProducto.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblCant.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtPrecioProducto.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtCant.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        btnProcesar.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPrecioProducto = new javax.swing.JLabel();
        lblCant = new javax.swing.JLabel();
        txtPrecioProducto = new javax.swing.JTextField();
        txtCant = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPrecioProducto.setText("Precio de producto :");

        lblCant.setText("Cantidad vendida :");

        txtPrecioProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioProductoKeyTyped(evt);
            }
        });

        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecioProducto)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnProcesar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCant)
                        .addGap(24, 24, 24)
                        .addComponent(txtCant)))
                .addGap(52, 52, 52))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProducto)
                    .addComponent(txtPrecioProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCant)
                    .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnProcesar)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        //Datos
        String txtPrecioProducto_text = txtPrecioProducto.getText();
        String txtCant_text = txtCant.getText();

        if (txtPrecioProducto_text.isEmpty()) {
            showJOP("INGRESE PRECIO DE PRODUCTO", "MENSAJE");
        } else if (txtCant_text.isEmpty()) {
            showJOP("INGRESE CANTIDAD", "MENSAJE");
        } else {
            double PrecioProducto;
            Integer Cant = null;
            try {
                PrecioProducto = Double.parseDouble(txtPrecioProducto_text);
                try {
                    Cant = Integer.parseInt(txtCant_text);
                    PP03Dto pP03Dto = new PP03Dto(PrecioProducto, Cant);
                    PP03Service service = new PP03Service();
                    pP03Dto = service.calcularTotal(pP03Dto);

                    //Reporte
                    String repo = "";
                    repo += "Importe: " + pP03Dto.getImporte() + "\n";
                    repo += "Impuesto: " + pP03Dto.getImpuesto() + "\n";
                    repo += "Total: " + pP03Dto.getTotal() + "\n";
                    //repo += "Impuesto: " + String.format("%.2f", pP03Dto.getImpuesto()) + "\n";
                    //repo += "Total: " + String.format("%.2f", pP03Dto.getTotal()) + "\n";

                    showJOP(repo, "REPORTE");
                } catch (NumberFormatException e) {
                    System.out.println(e);
                    showJOP("La cantidad no es numerica", "MENSAJE");
                }

            } catch (NumberFormatException e) {
                System.out.println(e);
                showJOP("El precio del producto no es numerico", "MENSAJE");
            }
        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtPrecioProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioProductoKeyTyped
        //JTextField accept only numbers and one dot
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)) || (c == evt.VK_PERIOD) || (c == evt.VK_BACK_SPACE)) {
            int punto = 0;
            if (c == evt.VK_PERIOD) {
                String s = txtPrecioProducto.getText();
                int dot = s.indexOf('.');
                punto = dot;
                if (dot != -1) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        } else {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioProductoKeyTyped

    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        /* if (Character.isDigit(evt.getKeyChar())) {
            super.processKeyEvent(evt);
        }
        evt.consume();*/
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)
                || (c == evt.VK_BACK_SPACE)
                || (c == evt.VK_DELETE))) {
            evt.consume();

        }
    }//GEN-LAST:event_txtCantKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PP03View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PP03View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PP03View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PP03View.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PP03View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblPrecioProducto;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtPrecioProducto;
    // End of variables declaration//GEN-END:variables

    private void showJOP(String message, String title) {
        JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

}
