/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.pedidoapp.view;

import java.awt.Font;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pe.egcc.pedidoapp.services.PedidoService;

/**
 * , 2), 2), 2), 2)
 *
 * @author Alumno-CT
 */
public class PedidoView extends javax.swing.JFrame {

    /**
     * Creates new form PedidoView
     */
    public PedidoView() {
        int LETTER_SIZE = 18;
        String ARIAL = "Arial";

        initComponents();
        this.setTitle("PEDIDOAPP");
        lblImporte.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtImporte.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        btnProcesar.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblImporte = new javax.swing.JLabel();
        txtImporte = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblImporte.setText("Importe");

        txtImporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtImporteKeyTyped(evt);
            }
        });

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImporte)
                .addGap(18, 18, 18)
                .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProcesar)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImporte)
                    .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProcesar))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        //Datos
        String importeText = txtImporte.getText();
        if (importeText.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "INGRESE VALOR", "REPORTE", JOptionPane.INFORMATION_MESSAGE);
        } else {
            double importe = 0;
            try {
                importe = Double.parseDouble(importeText);
                //double importe = 1000.0;
                PedidoService pedidoService = new PedidoService();
                double impuesto = pedidoService.calcularImpuesto(importe);
                double total = pedidoService.calcularTotal(importe);
                //Reporte
                String repo = "";
                repo += "Importe: " + importe + "\n";
                repo += "Impuesto: " + impuesto + "\n";
                //repo += "Impuesto: " + String.format("%.2f", impuesto) + "\n";
                repo += "Total: " + total + "\n";
                //repo += "Total: " + String.format("%.2f", total) + "\n";

                JOptionPane.showMessageDialog(rootPane, repo, "REPORTE", JOptionPane.INFORMATION_MESSAGE);
            } catch (NumberFormatException e) {
                System.out.println(e);
                JOptionPane.showMessageDialog(rootPane, "EL VALOR DEL IMPORTE NO ES NUMERICO", "REPORTE", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    private void txtImporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtImporteKeyTyped
        //JTextField accept only numbers and one dot
        char c = evt.getKeyChar();
        if ((Character.isDigit(c)) || (c == evt.VK_PERIOD) || (c == evt.VK_BACK_SPACE)) {
            int punto = 0;
            if (c == evt.VK_PERIOD) {
                String s = txtImporte.getText();
                int dot = s.indexOf('.');
                punto = dot;
                if (dot != -1) {
                    getToolkit().beep();
                    evt.consume();
                }
            }
        } else {
            getToolkit().beep();
            evt.consume();
        }

    }//GEN-LAST:event_txtImporteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblImporte;
    private javax.swing.JTextField txtImporte;
    // End of variables declaration//GEN-END:variables
}
