package pe.egcc.pp01app.view;

import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import pe.egcc.pp01app.dto.PP01AppDto;
import pe.egcc.pp01app.service.PP01AppService;

public class PP01View extends javax.swing.JFrame {

    /**
     * Creates new form PP01View
     */
    public PP01View() {
        int LETTER_SIZE = 15;
        String ARIAL = "Arial";
        initComponents();
        this.setTitle("PP01App");
        lblPract1.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblPract2.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblPract3.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblPract4.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtPract1.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtPract2.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtPract3.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtPract4.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        btnProcesar.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblExamParcial.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblExamFinal.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtExamParcial.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtExamFinal.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        btnProcesar.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPract1 = new javax.swing.JLabel();
        txtPract1 = new javax.swing.JTextField();
        lblPract2 = new javax.swing.JLabel();
        lblPract3 = new javax.swing.JLabel();
        lblPract4 = new javax.swing.JLabel();
        txtPract2 = new javax.swing.JTextField();
        txtPract3 = new javax.swing.JTextField();
        txtPract4 = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        lblExamParcial = new javax.swing.JLabel();
        lblExamFinal = new javax.swing.JLabel();
        txtExamParcial = new javax.swing.JTextField();
        txtExamFinal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Practicas"));

        lblPract1.setText("Practica n° 1 :");

        lblPract2.setText("Practica n° 2 :");

        lblPract3.setText("Practica n° 3 :");

        lblPract4.setText("Practica n° 4 :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPract1)
                        .addGap(18, 18, 18)
                        .addComponent(txtPract1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPract2)
                            .addComponent(lblPract3)
                            .addComponent(lblPract4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPract4)
                            .addComponent(txtPract2)
                            .addComponent(txtPract3))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPract1)
                    .addComponent(txtPract1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPract2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPract2))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPract3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPract3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPract4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPract4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        lblExamParcial.setText("Examen Parcial :");

        lblExamFinal.setText("Examen Final :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblExamParcial)
                            .addComponent(lblExamFinal))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtExamParcial, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtExamFinal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnProcesar)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExamParcial)
                    .addComponent(txtExamParcial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExamFinal)
                    .addComponent(txtExamFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnProcesar)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        //DATOS
        String txtPract1_text = txtPract1.getText();
        String txtPract2_text = txtPract2.getText();
        String txtPract3_text = txtPract3.getText();
        String txtPract4_text = txtPract4.getText();
        String txtExamParcial_text = txtExamParcial.getText();
        String txtExamFinal_text = txtExamFinal.getText();

        if (txtPract1_text.isEmpty()) {
            showJOP("Ingrese nota de practica n°1", "MENSAJE");
        } else if (txtPract2_text.isEmpty()) {
            showJOP("Ingrese nota de practica n°2", "MENSAJE");
        } else if (txtPract3_text.isEmpty()) {
            showJOP("Ingrese nota de practica n°3", "MENSAJE");
        } else if (txtPract4_text.isEmpty()) {
            showJOP("Ingrese nota de practica n°4", "MENSAJE");
        } else if (txtExamParcial_text.isEmpty()) {
            showJOP("Ingrese examen parcial", "MENSAJE");
        } else if (txtExamFinal_text.isEmpty()) {
            showJOP("Ingrese examen final", "MENSAJE");
        } else {
            try {
                double pract1 = Double.parseDouble(txtPract1_text);
                double pract2 = Double.parseDouble(txtPract2_text);
                double pract3 = Double.parseDouble(txtPract3_text);
                double pract4 = Double.parseDouble(txtPract4_text);
                double examenParcial = Double.parseDouble(txtExamParcial_text);
                double examenFinal = Double.parseDouble(txtExamFinal_text);

                ArrayList<Double> practicas = new ArrayList<>();
                practicas.add(pract1);
                practicas.add(pract2);
                practicas.add(pract3);
                practicas.add(pract4);

                PP01AppDto pP01AppDto = new PP01AppDto();
                pP01AppDto.setPracticas(practicas);
                pP01AppDto.setExamParcial(examenParcial);
                pP01AppDto.setExamFinal(examenFinal);

                PP01AppService service = new PP01AppService();
                pP01AppDto = service.calcularProm(pP01AppDto);

                //Reporte
                String repo = "";
                repo += "Promedio general: " + pP01AppDto.getPromGeneral() + "\n";
                //repo += "Promedio general: " + String.format("%.2f", pP01AppDto.getPromGeneral()) + "\n";

                showJOP(repo, "REPORTE");

            } catch (NumberFormatException e) {
                System.out.println(e);
                showJOP("Revise los datos ingresados", "MENSAJE");
            }

        }

    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PP01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PP01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PP01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PP01View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PP01View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblExamFinal;
    private javax.swing.JLabel lblExamParcial;
    private javax.swing.JLabel lblPract1;
    private javax.swing.JLabel lblPract2;
    private javax.swing.JLabel lblPract3;
    private javax.swing.JLabel lblPract4;
    private javax.swing.JTextField txtExamFinal;
    private javax.swing.JTextField txtExamParcial;
    private javax.swing.JTextField txtPract1;
    private javax.swing.JTextField txtPract2;
    private javax.swing.JTextField txtPract3;
    private javax.swing.JTextField txtPract4;
    // End of variables declaration//GEN-END:variables

    private void showJOP(String message, String title) {
        JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

}
