/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.pp02app.view;

import java.awt.Font;
import javax.swing.JOptionPane;
import pe.egcc.pp02app.service.PP02service;

/**
 *
 * @author Andy3
 */
public class PP02View extends javax.swing.JFrame {

    /**
     * Creates new form PP02View
     */
    public PP02View() {
        int LETTER_SIZE = 15;
        String ARIAL = "Arial";
        initComponents();
        this.setTitle("PP02App");
        lblcoord.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblc1.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        lblc2.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        jLabel3.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        jLabel4.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtX1.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtY1.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtX2.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        txtY2.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
        btnProcesar.setFont(new Font(ARIAL, Font.PLAIN, LETTER_SIZE));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblc1 = new javax.swing.JLabel();
        txtX1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtY2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lblc2 = new javax.swing.JLabel();
        txtX2 = new javax.swing.JTextField();
        btnProcesar = new javax.swing.JButton();
        lblcoord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblc1.setText("X1,Y1 :");

        jLabel3.setText(",");

        jLabel4.setText(",");

        lblc2.setText("X2,Y2 :");

        btnProcesar.setText("Procesar");
        btnProcesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesarActionPerformed(evt);
            }
        });

        lblcoord.setText("COORDENADAS :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblcoord)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnProcesar)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblc2)
                                .addGap(18, 18, 18)
                                .addComponent(txtX2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblc1)
                                .addGap(18, 18, 18)
                                .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcoord)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblc1)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblc2)
                    .addComponent(txtX2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(30, 30, 30)
                .addComponent(btnProcesar)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
        //DATOS
        String txtX1_text = txtX1.getText();
        String txtY1_text = txtY1.getText();
        String txtX2_text = txtX2.getText();
        String txtY2_text = txtY2.getText();

        if (txtX1_text.isEmpty()) {
            showJOP("INGRESE X1", "MENSAJE");
        } else if (txtY1_text.isEmpty()) {
            showJOP("INGRESE Y1", "MENSAJE");
        } else if (txtX2_text.isEmpty()) {
            showJOP("INGRESE X2", "MENSAJE");
        } else if (txtY2_text.isEmpty()) {
            showJOP("INGRESE Y2", "MENSAJE");
        } else {

            try {
                int x1 = Integer.parseInt(txtX1_text);
                int y1 = Integer.parseInt(txtY1_text);
                int x2 = Integer.parseInt(txtX2_text);
                int y2 = Integer.parseInt(txtY2_text);

                PP02service service = new PP02service();
                String cuadrante1 = service.cuadrante(x1, y1);
                String cuadrante2 = service.cuadrante(x2, y2);

                double distancia = service.distancia(x1, y1, x2, y2);
                //Reporte
                String repo = "";
                repo += "P1(" + x1 + "," + y1 + ") : Se encuentra en el " + cuadrante1 + "\n";
                repo += "P2(" + x2 + "," + y2 + ") : Se encuentra en el " + cuadrante2 + "\n";
                repo += "La distancia enre ambos puntos es :" + distancia + "\n";
                //repo += "La distancia enre ambos puntos es :" + String.format("%.2f", distancia) + "\n";
                showJOP(repo, "REPORTE");
            } catch (NumberFormatException e) {
                System.out.println(e);
                showJOP("Revise los datos ingresados", "MENSAJE");
            }

        }
    }//GEN-LAST:event_btnProcesarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PP02View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PP02View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PP02View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PP02View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PP02View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcesar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblc1;
    private javax.swing.JLabel lblc2;
    private javax.swing.JLabel lblcoord;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX2;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY2;
    // End of variables declaration//GEN-END:variables

    private void showJOP(String message, String title) {
        JOptionPane.showMessageDialog(rootPane, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
}
